---

- name: install packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
   - git
   - unzip
   - curl
   - dirmngr
   - apt-transport-https
   - lsb-release
   - ca-certificates
  become: yes
